site_name: SreeBase
site_description: The Bracketless, Enterprise-Grade NoSQL Database
site_author: "[Your Name]"
repo_url: "https://github.com/[YourUsername]/sreebase"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Query Syntax: syntax.md
  - Python SDK (reddybase): api.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
